# Generated by Django 4.0 on 2021-12-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ultimo_nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('profissao', models.CharField(max_length=200)),
            ],
        ),
    ]
