# Generated by Django 4.0 on 2021-12-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='criado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
